package com.lwd.jobportal.notification;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    NEW_MESSAGE,
    JOB_RECOMMENDED,
    PROFILE_VIEWED,
    RESUME_VIEWED,
    RESUME_DOWNLOADED,
    SUBSCRIPTION_ALERT,
    FEATURE_LIMIT_REACHED,
    NEW_APPLICATION_RECEIVED,
    JOB_EXPIRES_SOON,
    RECRUITER_APPROVAL_PENDING,
    SYSTEM_ALERT, 
}